name: "Brunata Fetcher"
description: "Scrapes the Brunata Nutzerportal and publishes energy sensor data via MQTT Discovery."
version: "0.1.6b9"
slug: "brunata_fetcher"
url: "https://github.com/MtheK/brunata-fetcher-ha-addon"
init: false
hassio_api: true
homeassistant_api: true
services:
  - "mqtt:want"
arch:
  - amd64
  - aarch64

options:
  email: ""
  password: ""
  energy_types:
    Heizung: true
    Kaltwasser: true
    Warmwasser: true
  scan_interval_hours: 24
  advanced:
    mqtt_host: ""
    mqtt_port: 1883
    mqtt_user: ""
    mqtt_password: ""
    scraper_url: "https://nutzerportal.brunata-muenchen.de/np_anmeldung/index.html?sap-language=DE"

schema:
  email: email
  password: password
  energy_types:
    Heizung: bool
    Kaltwasser: bool
    Warmwasser: bool
  scan_interval_hours: "int(1,168)"
  advanced:
    mqtt_host: "str?"
    mqtt_port: "port"
    mqtt_user: "str?"
    mqtt_password: "password?"
    scraper_url: "url?"
